### ISSUE TITLE
"Must use import to load ES Module" error within a CommonJS project when using pure ESM dependencies

### ISSUE THREAD

**Issue by ivangabriele** [swc-project/jest#102]
I'm not able to setup a Jest + SWC within a CommonJS project when using pure ESM dependencies and running jest via the experimental ESM option.

I keep getting this error:

```sh
 FAIL  ./index.test.ts
  ● Test suite failed to run

    Must use import to load ES Module: C:\Users\ivang\Workspace\ivangabriele\issue__@swc__jest\node_modules\ky-universal
\index.js

    > 1 | import ky from 'ky-universal'
        |                              ^
      2 |
      3 | export async function getBreweries() {
      4 |   const { data } = await ky.get('https://api.openbrewerydb.org/breweries').json()

      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:1010:21)
      at Object.<anonymous> (index.ts:1:30)
      at Object.<anonymous> (index.test.ts:1:33)
```

I have created a minimal repo to easily reproduce the issue:

https://github.com/ivangabriele/issue__swc-project__jest

Here is the command:

```sh
node --experimental-vm-modules ./node_modules/jest/bin/jest.js
```

Here is Jest config:

**jest.config.js**

```js
module.exports = {
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  transform: {
    '.*\\.(j|t)sx?$': ['@swc/jest'],
  },
  transformIgnorePatterns: [],

  // Doesn't work either with that:
  // transformIgnorePatterns: ['/node_modules/(?!ky-universal)'],
}
```

**Comment by simonhammes** [comment]
Adding `extensionsToTreatAsEsm: ['.ts']` to `jest.config.js` and installing the  required `ky` peer dependency worked for me when cloning your repository.

![image](https://user-images.githubusercontent.com/10352679/173195708-7ba03d26-701d-4f06-a064-d5ab1262656c.png)

**Comment by ivangabriele** [comment]
This worked indeed! Thank you very much @simonhammes :).
