### ISSUE TITLE
Using ttypescript and ts-auto-mock

### ISSUE THREAD

**Issue by Poliziano** [swc-project/jest#105]
I'm looking to switch a project from `ts-jest` to `@swc/jest`. This project uses `ttypescript` and `ts-auto-mock`, and requires `ts-jest` to be configured to use them:

```javascript
module.exports = {
  // [...]
  globals: {
    'ts-jest': {
      compiler: 'ttypescript'
    }
  }
};
```

Is it possible to achieve the same or similar in `@swc/jest`?

**Comment by kdy1** [comment]
Closing as wontfix

**Comment by kdy1** [comment]
@rattrayalex  swc already has Wasm plugin interface
