### ISSUE TITLE
[Typescript] Augmented enum is containing undefined

### ISSUE THREAD

**Issue by Smrtnyk** [swc-project/jest#106]
Clone the repo
https://github.com/Smrtnyk/swc-ts-repro

Run npm install
Run npm test

test fails because augmented enum is empty, but it should contain augmented keys
@kdy1 told me on discord that this scenario is supported, so maybe something in swc config is wrong?

If you run npm run build, in dist directory you will see that enum is correctly resolved with proper values

**Comment by kdy1** [comment]
This is not a supported case.
I meant declaration merging it supported
