### ISSUE TITLE
why jest coverage decrease compared with ts-jest

### ISSUE THREAD

**Issue by UNDERCOVERj** [swc-project/jest#112]
with @swc/jest

![image](https://user-images.githubusercontent.com/23290513/178228767-cfbb8e63-b1d6-4530-9352-cbc58e059e4d.png)

with ts-jest

![image](https://user-images.githubusercontent.com/23290513/178228921-a9ddc151-aaae-459b-a653-b1cd76ffbf55.png)

.swcrc

```
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "target": "es2018"
  },
  "module": {
    "type": "commonjs",
    "noInterop": true
  }
}

```

jest.config.js

```
/** @type {import('@jest/types').Config.InitialOptions} */
const config = {
  verbose: true,
  testMatch: ['**/api/**/*.test.[jt]s'],
  modulePaths: ['<rootDir>'],
  testPathIgnorePatterns: ['api/config', '/node_modules/', '/output/'],
  coveragePathIgnorePatterns: ['dto', 'mock'],
  setupFiles: ['./jest-setup-file.ts'],
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
};

module.exports = config;
```

**Comment by alexgwolff** [comment]
just for curiosity you can show your tsconfig?

**Comment by UNDERCOVERj** [comment]
> just for curiosity you can show your tsconfig?

{
  "compilerOptions": {
    "alwaysStrict": true,
    "declaration": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "importHelpers": false,
    "jsx": "preserve",
    "lib": [
      "DOM",
      "ES2019"
    ],
    "module": "CommonJS",
    "moduleResolution": "Node",
    "noImplicitAny": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "pretty": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "target": "ES2019",
    "useDefineForClassFields": true,
    "useUnknownInCatchVariables": true,
    "emitDecoratorMetadata": true,
    "paths": {
      "@lambda/*": [
        "./api/lambda/*"
      ],
      "@constants/*": [
        "./api/constants/*"
      ],
      "@models/*": [
        "./api/models/*"
      ],
      "@utils/*": [
        "./api/utils/*"
      ],
      "@rpc/*": [
        "./api/rpc/*"
      ],
      "@test/*": [
        "./api/__test__/*"
      ],
      "@mock/*": [
        "./mock/*"
      ]
    },
    "baseUrl": "./"
  },
  "exclude": [
    "**/node_modules/**",
    "types/**/*",
    "idlc.json",
    "scripts/template.ts"
  ],
  "include": [
    "*.ts",
    "mock",
    "api/**/*",
    "typings/**/*"
  ],
  "ts-node": {
    "module": "CommonJS",
    "transpileOnly": true,
    "swc": true,
    "require": [
      "tsconfig-paths/register"
    ]
  }
}

**Comment by klutzer** [comment]
Same issue here
