### ISSUE TITLE
TypeError: Cannot redefine property: default

### ISSUE THREAD

**Issue by k2xl** [swc-project/jest#118]
Trying to mock out a default exported function

`jest.spyOn(actual, 'default').mockReturnValue(timestamp as number * MINUTE);`

Worked in ts-jest, but getting 
```
    TypeError: Cannot redefine property: default
        at Function.defineProperty (<anonymous>)
```
With swc-jest

**Comment by Smrtnyk** [comment]
Try swc/core 197

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/issues/5205

**Comment by maschwenk** [comment]
Bump on @stephenh 's note. Shouldn't jest mocking continue to work if our module type is `commonjs`?
