### ISSUE TITLE
Add hoisting of the "@jest/globals" import together with jest.mock

### ISSUE THREAD

**Issue by webschik** [swc-project/jest#120]
In the next example the hoisting of the `jest.mock` doesn't work:

```js
// input
import {jest} from "@jest/globals";
import {foo} from './module1.js';
import {bar} from './module2.js';

jest.mock('./module1.js');
```

```js
// result code
"use strict";
var _globals = require("@jest/globals");
var _module1Js = require("./module1.js");
var _module2Js = require("./module2.js");
_globals.jest.mock('./module1.js');
```

Is it possible to update swc AST to hoist `jest.mock` before the `module1.js` and `module2.js` imports?

**Comment by koshic** [comment]
Any updates?

**Comment by Smrtnyk** [comment]
@kdy1 any plans on this?

**Comment by kdy1** [comment]
See https://github.com/swc-project/swc/issues/7435

**Comment by Smrtnyk** [comment]
I don't see what that document is supposed to reveal here?
This is about the jest.mock hositing which is already built in in swc, but doesn't cover this case
this basically breaks the functionality of jest

**Comment by kdy1** [comment]
> Is it possible to update swc AST to hoist jest.mock before the module1.js and module2.js imports?

I think you are talking about something different

**Comment by Smrtnyk** [comment]
I think the easiest is to remove import {jest} from "@jest/globals"; completely since it is not needed for jest.
Jest injects globals anyway.
It is only for typecript to have proper strict types in tests.
And hoist jest.mock as it is already hoisted without @jest/globals imports

**Comment by kdy1** [comment]
It's a different issue from this. Please file a new one instead.

**Comment by Smrtnyk** [comment]
I don't see how it is different
I see it as exactly the same issue, check my repository I linked
@webschik is the issue I am talking about the same as you are referring to?

**Comment by kdy1** [comment]
He want to mock ESMs, and it will never be supported. If your requirement is the same, it's also not planned.

**Comment by kdy1** [comment]
He want to mock ESMs, and it will never be supported. If your requirement is the same, it's also not planned.

**Comment by Smrtnyk** [comment]
ok let me explain myself
the issue is with jest.mock hoisting

swc already hoists jest.mock by default
but if you import jest from `@jest/globals` to get good types for typescript
swc stops hoisting jest.mock

that import is there purely for typescript, not for jest itself
tests work if you remove that import but types are not good

so what that import does is, it prevents swc from hoisting jest.mock properly as it was before
it is not about esm stuff, it is purely and only about jest.mock hoisting.

If swc would move jest.mock under that import, or remove that import completely and hoist jest.mock as before, then the behavior would be preserved.

**Comment by SimenB** [comment]
>Jest injects globals anyway.

Can be turned off via config. https://jestjs.io/docs/cli#--injectglobals

A quick hack might be to just remove the import, run the transform/hoisting, then reinject the import afterwards

**Comment by CMCDragonkai** [comment]
I have upstream code that I depend on that ends up using `@jest/globals` and we hit the same problem in https://github.com/dubzzz/fast-check/issues/4986.

Seems like @Smrtnyk is proposing monkeypatching the code during the transformation so that it doesn't break.

**Comment by CMCDragonkai** [comment]
> A quick hack might be to just remove the import, run the transform/hoisting, then reinject the import afterwards. Would be wrong if people alias the imports, but still

In our case it appears the imports are aliased.

> ```diff
> diff --git a/node_modules/@fast-check/jest/lib/jest-fast-check.js b/node_modules/@fast-check/jest/lib/jest-fast-check.js
> index 9fe5a3d..8d2c980 100644
> --- a/node_modules/@fast-check/jest/lib/jest-fast-check.js
> +++ b/node_modules/@fast-check/jest/lib/jest-fast-check.js
> @@ -1,5 +1,5 @@
>  import * as fc from 'fast-check';
> -import { it as itJest, test as testJest, jest } from '@jest/globals';
> +const { it: itJest, test: testJest, jest } = globalThis;
>  import { buildTest } from './internals/TestBuilder.js';
>  export const test = buildTest(testJest, jest, fc);
>  export const it = buildTest(itJest, jest, fc);
> ```
