### ISSUE TITLE
Cannot read properties of undefined (reading 'html') when using jsdom environment

### ISSUE THREAD

**Issue by dunklesToast** [swc-project/jest#122]
Hey,

we're having some tests with React Components which require us to have a "real" browser environment. We're using JSDom for that.

So let's say our test setup includes this file:

```js
window.matchMedia =
  window.matchMedia ||
  function () {
    return {
      matches: false,
      addListener: function () {},
      removeListener: function () {},
    };
  };
```

this will result in an error:

```
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'html')

      at new JSDOMEnvironment (../../node_modules/jest-environment-jsdom/build/index.js:72:44)
```

Removing `jsdom` as test env is not suitable since that will result in other errors:

```
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: window is not defined

      1 | /* eslint-disable */
    > 2 | window.matchMedia =
        | ^
      3 |   window.matchMedia ||
      4 |   function () {
      5 |     return {

      at Object.window (src/test-setup.js:2:1)
```

The jest config looks like this:

```js
module.exports = {
  transform: {
    '^.+\\.(t|j)sx?$': '@swc/jest',
  },
  testEnvironment: 'jsdom',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  resetMocks: true,
  bail: false,
  setupFilesAfterEnv: [
    './src/test-setup.js',
  ],
  moduleNameMapper: {
    '\\.(css)$': 'identity-obj-proxy',
  }
};
```

Any idea how to fix this issue or do these `@swc/jest` bindings not work with `jsdom`.

**Comment by Smrtnyk** [comment]
I think this is not a swc/jest issue.
Can you try babel or ts-jest in combination?

**Comment by dunklesToast** [comment]
Okay it seemed that I've installed an outdated version of `jest-environment-jsdom`. With version 29 it worked. I now have a problem with `jest-styled-components` but cannot reproduce that, so i assume it's also on my side. Sorry to bother and thanks for the quick response!
