### ISSUE TITLE
Please add `babelConfig` like `ts-jest` does

### ISSUE THREAD

**Issue by matthew-dean** [swc-project/jest#127]
There are lots of instances where we want to migrate from `babel-jest` / `ts-jest` to `@swc/jest` but it's just not possible, because of lack of support of additional Babel transforms. Meaning it's not really a drop-in replacement.

What `ts-jest` does is, after transforming, it passes the result to Babel for additional transformations. (Maybe this is pointless from a performance perspective, I'm not sure?)

So, it would be nice to have a `babelConfig` option to do some additional transformations not supported by SWC. See: https://kulshekhar.github.io/ts-jest/docs/getting-started/options/babelConfig

**Comment by kdy1** [comment]
I'll not add this as it will be very slow
