### ISSUE TITLE
InversifyJS + NX + @swc/jest IocContainer or container is undefined in test

### ISSUE THREAD

**Issue by jcjp** [swc-project/jest#129]
- When using this library along with inversifyjs and nx/nrwl, `container` from inversifyjs is `undefined`.
 - Adding the `inversify.config.ts` on the` setupFiles` throws out a different error of `reflectMetadata.<function> is not a function`.
 - `reflect-metadata` is imported at the root entry file and at the first line.

**Comment by kdy1** [comment]
Please file an issue on the main repository with repro case
