### ISSUE TITLE
Import are not done in the same order as jest

### ISSUE THREAD

**Issue by bodinsamuel** [swc-project/jest#13]
Hello,

I was trying to use swc, performance seems great and everything was quite smooth.
However I hit two issues, the main one being about import order.

With a scenario like this:
```js
my.test.ts
  -> import file.ts
```

In classic jest, `my.test.ts` is executed and then `file.ts`
With `@swc/jest` it's the opposite (first `file.ts` then `my.test.ts`) 

It's mostly fine, but it can **break mocking and changing global var.**
In my case, `my.test.ts` was modifying `process.env` first so that the rest of code act accordingly and it no longer works with swc. There are alternatives and could be expected, but I think it's worth pointing in case it was not intended behavior.

Best Regards

**Comment by kdy1** [comment]
This is a bug of jest. ES Specification defines the execution order.
