### ISSUE TITLE
plugins squashed when outstanding plugins present

### ISSUE THREAD

**Issue by cdaringe** [swc-project/jest#133]
# Problem

If a plugin is present, is is squashed against expectation.

# Discussion

https://github.com/swc-project/jest/pull/94/files#diff-dcdc3e0b3362edb8fec2a51d3fa51f8fb8af8f70247e06d9887fa934834c9122R131-R133

```js
  if (!Array.isArray(!swcTransformOpts.jsc.experimental.plugins)) {
    swcTransformOpts.jsc.experimental.plugins = []
  }
```

It seems incorrect that there is a leading negation `!` here. It coerces `undefined | T[]` into a bool, then we do an array check on a bool.

Perhaps

```js
  if (!Array.isArray(swcTransformOpts.jsc.experimental.plugins)) {
    swcTransformOpts.jsc.experimental.plugins = []
  }
```

is what is desired?

**Comment by kdy1** [comment]
I think so?

**Comment by kdy1** [comment]
https://github.com/swc-project/jest/commit/08419c0d91b4952e50b519cf378ada85636b0be9
