### ISSUE TITLE
should not transpile nullish coalescing operator and optional chaining in node 18

### ISSUE THREAD

**Issue by unional** [swc-project/jest#136]
It is a pretty odd case.

When running on node 14 and 16, nullish coalescing operator and optional chaining are not transpiled (correctly).

But when running on node 18, they got transpiled:

```sh
    Expected: "fn oc(s) { return s?.a }"
    Received: "fn oc(s) { return s === null || s === void 0 ? void 0 : s.a }"

    Expected: "fn nco(s) { return s ?? 1 }"
    Received: "fn nco(s) { return s !== null && s !== void 0 ? s : 1 }"

    Expected: "fn() { try { return 1 } catch { return 2 } finally { console.info(3) } }"
    Received: "fn() { try { return 1 } catch (e) { return 2 } finally { console.info(3) } }"
```

Seems like somehow node 18 is treated like node 12?

Here are the failed tests:
https://github.com/unional/tersify/actions/runs/3667770830/jobs/6200450813

To repro, check out the repo and switch to the `buddy` branch.

Run `pnpm test:swc`

**Comment by christiango** [comment]
Looks like we need to update the mapping here to include newer versions of node: https://github.com/swc-project/jest/blob/master/index.ts#L96
