### ISSUE TITLE
Branch not coverad

### ISSUE THREAD

**Issue by elvesbd** [swc-project/jest#137]
I'm using version 16.18.1 of node and my application is built with NestJS framework, when configuring @swc/jest in my project my tests run perfectly, but the coverage report says that only 50% of the branches were covered. I'm using "@swc/core": "^1.3.23", "@swc/jest": "^0.2.24".
`.swcrc
{
  "sourceMaps": true,
  "module": {
    "type": "commonjs",
    "strict": true
  },
  "jsc": {
    "target": "es2020",
    "parser": {
      "syntax": "typescript",
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "keepClassNames": true
  }
}
`
`jest.config.js
module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': '@swc/jest',
  },
  collectCoverageFrom: ['**/*.(t|j)s'],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
};

`

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/issues/3854
