### ISSUE TITLE
Source maps incorrect for errors thrown by imported modules

### ISSUE THREAD

**Issue by davidtheclark** [swc-project/jest#138]
When an assertion in my test file fails, or an error is thrown in the test file, source maps seem to be accurate. But when an error is thrown from one of the imported modules, the source maps are incorrect.

For example, here's a snippet where I'm throwing an error on line 10:

<img width="621" alt="Screenshot 2022-12-28 at 07 15 16" src="https://user-images.githubusercontent.com/628431/209825633-db799e46-8c30-405b-8a19-3bac6ab753af.png">

And here's the Jest output that points incorrectly to line 21 -- both the stack trace and the code frame are incorrect:

<img width="736" alt="Screenshot 2022-12-28 at 07 16 34" src="https://user-images.githubusercontent.com/628431/209825675-153a1bb6-bd27-404f-85f1-88e4e9be4d87.png">

That last line in the Jest output is correctly pointing to line 17 of the test file, though; only errors from the imported module show this bug:

<img width="463" alt="Screenshot 2022-12-28 at 07 18 10" src="https://user-images.githubusercontent.com/628431/209825801-d3264a76-e0bc-4fd0-951d-cbf93fdc8391.png">

Here is the `.swcrc` file that is being used:

```
{
  jsc: {
    parser: {
      syntax: 'typescript',
      tsx: true,
      decorators: true,
      dynamicImport: true
    },
    target: 'es2021'
  },
  module: { type: 'commonjs' },
  sourceMaps: true
}
```

**Comment by kdy1** [comment]
Please create a new issue on [the main swc repository](https://github.com/swc-project/swc) with repro case

**Comment by scamden** [comment]
fwiw trial and error found that switching to `sourceMaps : "inline"` fixed this. i'm wondering if something is off about the `map` property returned by this jest transform at least for jest 29.

not sure why this was closed or asked to be moved because i'm 90% sure this is in fact a problem with the jest transform specifically.

**Comment by kdy1** [comment]
jest code lives in the main repository, and more importantly, currently `jest` repository does not have a good form

**Comment by scamden** [comment]
Ok thanks for the explanation. I'll open an issue there

**Comment by scamden** [comment]
for anyone finding this upgrading to `@swc/core : 1.3.31` fixed this.
