### ISSUE TITLE
@ts-ignore still throws error

### ISSUE THREAD

**Issue by DiamondMofeng** [swc-project/jest#140]
I am working on a [grafana plugin](https://github.com/DiamondMofeng/grafana-greptime-datasource). The repo was generated by their official tool and uses @swc/jest as transformer. [The jest config is here](https://github.com/DiamondMofeng/grafana-greptime-datasource/blob/main/.config/jest.config.js#L24)

[One of Grafana's official dependencies has a `//@ts-ignore` commit on it](https://github.com/grafana/grafana/blob/main/packages/grafana-runtime/src/utils/DataSourceWithBackend.ts#L410), but the error is not ignored and blocks me from running my test cases.

I have tried allowing relevant rules in eslint, and still have no idea how to solve this problem. 

![J43OA)YPD5NKX`(S{UG%RXA](https://user-images.githubusercontent.com/52260316/216008124-66aa648b-a349-47fc-ab97-108d595ef9ce.png)
![PD1@K9 A%SK__L7(BS$8B1S](https://user-images.githubusercontent.com/52260316/216008144-d5ff8c08-9982-4446-8ea0-bfc0e833e235.png)

**Comment by kdy1** [comment]
Please report this to the main swc repository.
This is quite close to https://github.com/swc-project/swc/issues/4512, although it's about disabling **all** checks
