### ISSUE TITLE
Broken by 1.3.35 of `@swc/core`

### ISSUE THREAD

**Issue by Aghassi** [swc-project/jest#142]
I don't have a repro yet, but I've come across a situation with a vite project where upgrading `@swc/core` to `1.3.35` break `jest.spyOn` with the following error 

```sh
    TypeError: Cannot redefine property: useIsMember
        at Function.defineProperty (<anonymous>)

      4 | export function mockUseIsMemberTrue(...experimentNames: ExperimentName[]) {
      5 |   jest
    > 6 |     .spyOn(useExperimentVariant, 'useIsMember')
        |      ^
      7 |     .mockImplementation(experimentName =>
      8 |       experimentNames.includes(experimentName)
      9 |     )
```

This was working on version `1.2.159` of `@swc/core` with `@swc/jest` `0.2.20`.

I'm assuming that something changed with how tranpilation is done and now something is ending up being a `const` that shouldn't be. I'm not sure how best to debug this.

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/issues/5205
