### ISSUE TITLE
Context is undefined while initialising state for class component 

### ISSUE THREAD

**Issue by MDAkramSiddiqui** [swc-project/jest#146]
Getting this context is undefined error when I am initialising my class component state with context in a test, this seems to be happening only in swc jest not in ts-jest.

```
TypeError: Cannot read properties of undefined (reading 'working')

      23 |     console.log("LOG::", this.context);
      24 |     return {
    > 25 |       isContextWorking: this.context.working,
         |                                      ^
      26 |     };
      27 |   }
      28 | }
```
sandbox (with swc/jest) - https://codesandbox.io/p/sandbox/react-context-and-swc-jest-g0mq1t
sandbox (with ts-jest) - https://codesandbox.io/p/sandbox/happy-hofstadter-hnhhg3

Cmd for running test for both is ```npm run test```

**Comment by kdy1** [comment]
Please file an issue on the main repository instead

**Comment by MDAkramSiddiqui** [comment]
are these sandbox links not working ?
