### ISSUE TITLE
swcrc is imported again after having removed fields in jest config, or changing them

### ISSUE THREAD

**Issue by Codex-** [swc-project/jest#147]
Reproduction repo: https://github.com/Codex-/swc-jest-config-bug

Trying to use the same `.swc` for testing as you do for building causes tests to not work, even if you load and provide the config with the exclusions removed to `@swc/jest`:
```js
const fs = require("node:fs");
const process = require("node:process");

const config = JSON.parse(fs.readFileSync(`${process.cwd()}/.swcrc`, "utf-8"));
delete config.exclude;

/**
 * @type { import("jest").Config }
 */
module.exports = {
  transform: {
    "^.+\\.(t|j)sx?$": ["@swc/jest", config],
  },
  rootDir: __dirname,
  roots: ["<rootDir>/src"],
  testRegex: "(test|spec).tsx?$",
};
```

`jest` output:
```
➜  swc-jest-config-bug npx jest
 FAIL  src/utility.spec.ts
  ● Test suite failed to run

    cannot process file because it's ignored by .swcrc

      at Compiler.transformSync (node_modules/@swc/core/index.js:241:29)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.537 s
```

The same also occurs if you try to set exclude to an empty collection.

I would expect when providing a config manually that it does not also try and load the .swcrc again.

When logging the result of `buildSwcTransformOpts`, it appears as though this plugin does respect the options provided, however when actually trying to build it seems as though core or something else ignores this and reloads the swcrc anyway

**Comment by kdy1** [comment]
Please post your `.swcrc`. I'll reopen this once you post it.

**Comment by kdy1** [comment]
Nevermind, I missed the repro

**Comment by kdy1** [comment]
You can do
``js`
const fs = require("node:fs");
const process = require("node:process");

const config = JSON.parse(fs.readFileSync(`${process.cwd()}/.swcrc`, "utf-8"));
delete config.exclude;
config.swcrc = false;
```

**Comment by Codex-** [comment]
Great, thank!

Would be really helpful if this was added to the docs (or maybe I missed it?)
