### ISSUE TITLE
`.swc` directory is created

### ISSUE THREAD

**Issue by GreenTea124** [swc-project/jest#149]
When I run tests using `@swc/jest: 0.2.26` and `jest: 29.5.0` a following empty directory is created:
`.swc/plugins/v6_windows_x86_64_0.95.7`

Is it possible to prevent that or move it somewhere else (like `node_modules`)?

**Comment by Smrtnyk** [comment]
why is it bothering you?
just add it to .gitignore

**Comment by GreenTea124** [comment]
@Smrtnyk Added, I also added it to VSCode `files.exclude` so I don't see it. But it does seem like bug so I reported it.

**Comment by kdy1** [comment]
It's not a bug
