### ISSUE TITLE
Jest: clone is not a function

### ISSUE THREAD

**Issue by ammmze** [swc-project/jest#154]
I recently tried to switch to `@swc/jest` from `ts-jest` (to see if it would resolve issues I'm experiencing with jest mock stuff) and that very quickly came to halt. Upon the first run I was greeted with an error "clone is not a function". It looks like the "clone" function is [used by `graceful-fs`](https://github.com/isaacs/node-graceful-fs/blob/234379906b7d2f4c9cfeb412d2516f42b0fb4953/graceful-fs.js#L96) and [imported from it's own `clone.js`](https://github.com/isaacs/node-graceful-fs/blob/234379906b7d2f4c9cfeb412d2516f42b0fb4953/graceful-fs.js#L4). But I can't seem to find the combination to allow it to properly get that clone function. This only appears to be an issue with `@swc/jest` as best I can tell.

[Here](https://github.com/ammmze/swc-clone-is-not-function) is a repository that reproduces this issue along with github actions workflow showing the failure with `@swc/jest`, but success using `ts-jest`. Any idea what I'm missing here?

```
$ TEST_PRESET=@swc/jest npm test

> clone-not-function@1.0.0 test
> jest

FAIL  src/index.test.ts
● Test suite failed to run

    TypeError: clone is not a function

    at Object.<anonymous> (node_modules/graceful-fs/graceful-fs.js:96:24)
    at Object.<anonymous> (node_modules/expect/build/toThrowMatchers.js:9:24)
    at Object.<anonymous> (node_modules/expect/build/index.js:23:48)
    at _expect (node_modules/@jest/expect/build/index.js:8:16)
    at createJestExpect (node_modules/@jest/expect/build/index.js:29:3)
    at Object.<anonymous> (node_modules/@jest/expect/build/index.js:39:20)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.675 s, estimated 2 s
Ran all test suites.

```

This was also mentioned at one point in the jest project [here](https://github.com/jestjs/jest/issues/11858), but nobody came forward with steps to reproduce it over there.

**Comment by kdy1** [comment]
This does not look like a bug of swc

**Comment by kdy1** [comment]
One cause I can think of is a difference of module transforms. Try ignoring some packages from jest transformer config.

**Comment by ammmze** [comment]
Ooh 🤦🏻‍♂️ It's because I had put `@swc/jest` in `moduleNameMapper` not `transform`.
