### ISSUE TITLE
"SyntaxError: Unexpected identifier" for AsyncDisposable

### ISSUE THREAD

**Issue by ffMathy** [swc-project/jest#158]
Here's my test:

```typescript
test("disposeAsync", async () => {
    class AsyncDisposableExample implements AsyncDisposable {
        async [Symbol.asyncDispose]() { }
    }

    await using asyncDisposable = new AsyncDisposableExample();
})
```

I am getting the error:

>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
> 
>     Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
> 
>     By default "node_modules" folder is ignored by transformers.
> 
>     Here's what you can do:
>      • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
>      • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/configuration
>     For information about custom transformations, see:
>     https://jestjs.io/docs/code-transformation
> 
>     Details:
> 
>     /workspace/src/apps/redacted/redacted.test.ts:20
>                 await using asyncDisposable = new AsyncDisposableExample()
>                             ^^^^^^^^^^^^^^^
> 
>     SyntaxError: Unexpected identifier
> 
>       at Runtime.createScriptFromCode (../../../node_modules/.pnpm/jest-runtime@29.6.4/node_modules/jest-runtime/build/index.js:1505:14)

I am using NX and PNPM.

Relevant package versions: 
```json
"devDependencies": {
    "@nrwl/cli": "^15.9.3",
    "@nrwl/node": "16.7.4",
    "@nx/esbuild": "16.7.4",
    "@nx/eslint-plugin": "16.7.4",
    "@nx/jest": "16.7.4",
    "@nx/js": "16.7.4",
    "@nx/linter": "16.7.4",
    "@nx/node": "16.7.4",
    "@swc/cli": "^0.1.62",
    "@swc/core": "^1.3.80",
    "@swc/jest": "^0.2.29",
    "jest": "^29.6.4",
    "nx": "16.7.4",
    "reflect-metadata": "^0.1.13",
    "swc-loader": "^0.2.3",
    "ts-loader": "^9.4.4",
    "ts-mockito": "^2.6.1",
    "ts-node": "10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "~5.2.2"
}
```

My `.swcrc` looks like this:
```json
{
    "$schema": "https://json.schemastore.org/swcrc",
    "exclude": [],
    "jsc": {
      "parser": {
        "syntax": "typescript",
        "decorators": true
      },
      "target": "esnext",
      "externalHelpers": true,
      "transform": {
        "decoratorMetadata": true
      }
    },
    "minify": false
  }
```

My Jest config looks like:
```typescript
/* eslint-disable */
export default {
  displayName: 'r',edacted
  preset: '../../../jest.preset.js',
  testEnvironment: 'node',
  transform: {
    '^.+\\.[tj]s$': ['@swc/jest'],
  },
  moduleFileExtensions: ['ts', 'js', 'html'],
  setupFiles: ['<rootDir>/jest.setup.ts'],
  coverageDirectory: '../../../coverage/src/apps/redacted'
};
```

**Comment by kdy1** [comment]
This is not a bug of swc and your config seems wrong.

https://play.swc.rs/?version=1.3.74&code=H4sIAAAAAAAAAytJLS7RUErJLC7IL051LK7MS1bSUUgE0Qoamgq2dgrVXApAkJyTWFysAJZ3AatNTMpJda1IzC3ISVXIBJG5qXklGCqgukEAYmZ0cGVuUn6OXiJCXWos0KJqhVqwylouMJVYnphZolBanJmXrpCIZqStQl5qOQ6naGhac9VqAgAGxqii1AAAAA%3D%3D&config=H4sIAAAAAAAAA32VS47bMAyG9zlF4HUXbRcDtAformcQFItyNJVFQ6QyMQa5eyk%2FMkFMZxPE%2FPiTMknRn4fjsXmntvl9%2FJS%2F8jDYTJDvz2KhMbG9iqXhcQBqcxi4%2BbZSpoq8jQST6TaThm3ugKsK6Of3H78WRRMRCVbFYutDCn58zNnb1MUnNzG32A8ZiB5cxSqZSg%2BJ6dl%2FYhk%2FKuBcHu0nxAg2vSDGkgmJoYOsBW4xRjsQmIvNSpR6UpsDoZaiwsLgzJBxUHlygQMmybmlDqwzLTpQUMjQcriAJpNcIkuE28Ku2MGpdN3U%2Fic1XGwslpWccJ1aIqdVop4xEBtfklbCGe7UYIZLcZ%2BVwZsMXHLa6t4xpJ2e%2FAOQCkRLlGwPWtzJw8s87an9S2VIXiaZR4XL2GtvmaCTopoQvFLZWhnIHLRuZnClhVrZVjvOgnfKR8GBAe9lVpTQ9BG4PWtJ6%2F1HrwDpr%2FXaVM3A3G%2FhDq8X4gX%2BI2%2FJ%2BoAtHr3l8z6lsT9hfJGgBz6je%2BEgrWDcx1m2xHXY5yU5kNEAp7oUmsB2CcgFYDRxWqOb2ZDrIRFNF%2FH0tSYWh9th%2FZ3W8deCvSdvAv1FV%2BLj2DX9alm%2BBbXf8wZ%2Fa2qsw%2B0%2FJ8MDITAGAAA%3D

**Comment by ffMathy** [comment]
But in that link, the using statement is still present. And jest-runtime then gives me the exception.

I was under the impression that SWC was supposed to turn typescript features into something jest would understand. But perhaps the real issue is that jest doesn't understand asyncDispose?

**Comment by kdy1** [comment]
It's going to be fixed in the next version

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/issues/7879

**Comment by ffMathy** [comment]
Yay! Thanks for recognizing the bug. Can't wait for that release! I hope it comes out soon ❤️ 

You rock by the way. SWC is awesome, and I am looking forward to seeing STC being out too.
