### ISSUE TITLE
Cannot find module error after upgrading `@swc/core`

### ISSUE THREAD

**Issue by sacummings91** [swc-project/jest#161]
Hello, I recently upgraded `@swc/core` from `1.3.74` -> `1.3.82`. After doing this when I run tests I get `Cannot find module '../types/index.js' from '...'`. For some reason it is trying to find the file as a `.js` file instead of a `.ts` file. 

I tested each `@swc/core` version incrementally and can confirm that it is working up to `1.3.78` but breaks when switching to `1.3.79`.

Here are my config files: 

`.swcrc`
```
{
  "$schema": "https://json.schemastore.org/swcrc",
  "exclude": ["./lib"],
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": true
    },
    "target": "es2022",
    "paths": {
      "@ternary/api-lib/*": ["./sub-modules/api-lib/src/*"],
      "@ternary/web-ui-lib/*": ["./sub-modules/api-lib/src/ui-lib/*"]
    },
    "baseUrl": "."
  },
  "module": {
    "type": "commonjs"
  }
}
```

`jest.config.js`
```
module.exports = {
  transform: {
    "^.+\\.(t|j)sx?$": "@swc/jest",
  },
  testEnvironment: "node",
  collectCoverage: true,
  moduleNameMapper: {
    "^@ternary/api-lib/(.*)$": "<rootDir>/sub-modules/api-lib/src/$1",
  },
};
```

**Comment by kdy1** [comment]
Already fixed by https://github.com/swc-project/swc/pull/7906
