### ISSUE TITLE
Example with React

### ISSUE THREAD

**Issue by poteirard** [swc-project/jest#2]
I'm trying to move from `react-scripts` to SWC.

The building part is fine with webpack but I'm struggling a bit with jest.

this is the config that I've tried so far in the `package.json`:

```json
{
"jest": {
    "rootDir": "./src",
    "testMatch": ["<rootDir>/**/*.test.{ts,tsx,js,jsx}"],
    "moduleFileExtensions": ["ts", "tsx", "js", "jsx", "json", "node"],
    "transform": {
      "^.+\\.tsx?$": ["@swc/ject"]
    },
    "testEnvironment": "node",
    "collectCoverageFrom": [
      "src/components/**/*.{ts,tsx}"
    ]
  },
}
```

Any clue how to configure it properly?

The error I get in every test is:

> SyntaxError: Cannot use import statement outside a module

Thank you

**Comment by kdy1** [comment]
It seems like a bug of swc/jest.



Can you try module.type="commonjs" like shown below?

https://swc-project.github.io/docs/configuring-swc.html#common-js

**Comment by poteirard** [comment]
Hey @kdy1 same error 😓

**Comment by kdy1** [comment]
I'll fix it soon

**Comment by kdy1** [comment]
I found that it works if `rootDir` is removed

**Comment by kdy1** [comment]
Found the root cause.
You need to add `"<rootDir>/*.test.{ts,tsx,js,jsx}"` if you use `rootDir`, because `<rootDir>/File.tsx` does not match `**/*.tsx`.

I also added an example.

https://github.com/swc-project/jest/blob/6281cfbfdb63562acbca4fcdf49e7ea77c562e57/examples/react/package.json#L17-L37

**Comment by poteirard** [comment]
Hey @kdy1 thanks for your fast reply.

I tried the same config and got this error: 

```$ jest
● Validation Error:

  Module ../../.. in the transform option was not found.
         <rootDir> is: /Users/gerard.brull/DEV/react-components/src

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html
```

**Comment by kdy1** [comment]
You should use `@swc/jest` instead of `../../..`.

Example uses local dependency to check if current version works properly

**Comment by poteirard** [comment]
ah yes! I'm stupid 😅  sorry about that!

**Comment by kdy1** [comment]
No problem

**Comment by poteirard** [comment]
I'm spiking on migrating `react-scripts` with [react-stylegudist](react-styleguidist.js.org/) to SWC in case someone is interested in this https://github.com/zopaUK/react-components/pull/591
