### ISSUE TITLE
Incorrect line numbers in Jest output if sourceMaps are not enabled

### ISSUE THREAD

**Issue by srmagura** [swc-project/jest#25]
## Example

I put `throw new Error('TEST ERROR')` in one of my test files.

### Source maps not enabled in `.swcrc`

Jest output shows the failure occurring at the wrong line:

```text
 FAIL  src/__tests__/Skeleton.test.tsx
  ● disables the animation if and only if enableAnimation is false

    TEST ERROR

      68 |     expect(skeleton).toHaveClass('react-loading-skeleton')
      69 |     expect(skeleton).toHaveClass('test-class')
    > 70 | })
         |   ^
      71 |
      72 | it('applies the containerClassName and containerTestId', () => {
      73 |     render(<Skeleton containerClassName="test-class" containerTestId="myTestId" />)

      at Object.<anonymous> (src/__tests__/Skeleton.test.tsx:70:11)
```

### Source maps enabled in `.swcrc`

Jest output shows the failure occurring at the correct line:

```text
 FAIL  src/__tests__/Skeleton.test.tsx     
  ● disables the animation if and only if enableAnimation is false

    TEST ERROR

      58 |     expect(skeleton.style.animation).toBe('none')
      59 |
    > 60 |     throw new Error('TEST ERROR')
         |           ^
      61 | })
      62 |
      63 | it('uses a custom className', () => {

      at Object.<anonymous> (src/__tests__/Skeleton.test.tsx:60:11)
```

## Possible Solutions

* _If this behavior is unintended,_ fix the bug. (I can provide a minimal reproducible example.)
* Update https://swc.rs/docs/usage-swc-jest to recommend enabling source maps in `.swcrc`.
* (?) Automatically enable source maps in the `@swc/jest` code.

## Additional Context

This occurred in a React `.tsx` file.

`.swcrc`:
```json
{
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "tsx": true,
            "dynamicImport": true
        },
        "target": "es2021"
    },
    "module": {
        "type": "commonjs"
    }
}
```

**Comment by joshyudeep** [comment]
@srmagura - any chance you run into this issue? https://github.com/swc-project/jest/issues/47#issue-1062636830

**Comment by Thisen** [comment]
Any status on this?

**Comment by stephenh** [comment]
Fwiw I'm also getting in correct line numbers, not in the Jest output, but just in the stack traces themselves.

I've tried `.swcrc` enabling them, but that didn't fix it; using the `@swc-node/jest` project, the line numbers "just worked" the first time, so I'm going to use that for now.

**Comment by kdy1** [comment]
Can you try enabling source maps?

**Comment by stephenh** [comment]
Thanks for changing the default!

I tried the latest `@swc/jest: 0.2.16` and thought it was still broken, but run `jest --clearCache` made it work great!

Fwiw that could have been my error before, is that I'd made a `.swcrc` w/`sourceMaps: true` in it, but hadn't cleared the Jest cache, so was seeing stale/cached transformed results from Jest.

**Comment by aaronncfca** [comment]
I'm facing this issue even with sourceMaps:true, even after clearing the cache! Tests run but line numbers a good bit off. I don't want to spam a closed issue, but I'm not sure what else to try. Let me know if any suggestions!

Here's an exerpt of my .swcrc:
```
{
    "jsc": {
      "target": "es2017",
      "parser": {
        "syntax": "ecmascript",
        "jsx": true, [...]
      },
        "react": {
          "pragma": "React.createElement", [...]
        }
        "hidden": {
          "jest": true
        }
      }
    },
    "sourceMaps": true,
    "module": {
      "type": "commonjs", [...]
    }
  }
```

**Comment by thantos** [comment]
> I'm facing this issue even with sourceMaps:true, even after clearing the cache! Tests run but line numbers a good bit off. I don't want to spam a closed issue, but I'm not sure what else to try. Let me know if any suggestions!
> 
> Here's an exerpt of my .swcrc:
> ```
> {
>     "jsc": {
>       "target": "es2017",
>       "parser": {
>         "syntax": "ecmascript",
>         "jsx": true, [...]
>       },
>         "react": {
>           "pragma": "React.createElement", [...]
>         }
>         "hidden": {
>           "jest": true
>         }
>       }
>     },
>     "sourceMaps": true,
>     "module": {
>       "type": "commonjs", [...]
>     }
>   }
> ```

Ever solve this?

Seeing the same issue when minify is on. One by one or two lines.

**Comment by lmexo** [comment]
I faced the same issue, clearing cache and `sourceMaps: true` did not work. But it worked when using `sourceMaps: 'inline'`

**Comment by JasonKleban** [comment]
In my case, I think this might happen because of elided, unused imports or imported identifiers (on their own lines).  Not sure about that.
