### ISSUE TITLE
vscode-jest extension fails when trying to use swc (x64 vs arm64), with solution

### ISSUE THREAD

**Issue by vvo** [swc-project/jest#29]
Hi there, I've been able to setup `@swc/jest` in my project. It works on the command line via `npx jest` but not in vscode

Inside vscode I get this error:

```
  ● Test suite failed to run

    Can not load bindings
    Installed packages: [core-darwin-arm64]

      at loadBinding (node_modules/@node-rs/helper/lib/loader.js:50:11)
      at Object.<anonymous> (node_modules/@swc/core/index.js:37:43)
      at Object.<anonymous> (node_modules/@swc/jest/index.js:35:14)
```

After some debugging (console.log in lib/loader), I found out that the VSCode terminal runs on x64 architecture while my computer is a M1 (arm64).

I've tried to force VSCode to use arm64 inside the terminal without luck, I did not find any github issue about that also.

What I've done instead is:

```
npm i -D @swc/core-darwin-x64 --force
```

And now it works. Not sure what we could do to better support this. Thanks!

**Comment by kdy1** [comment]
This is bug of vscode, not `swc/jest`
