### ISSUE TITLE
_interopRequireWildcard is not defined

### ISSUE THREAD

**Issue by DoneDeal0** [swc-project/jest#30]
All my tests run, except those that deal with files which have wildcard imports or exports. (ex: `import * from "./myfile"`)

Like babel, swc/jest transforms wildcard  import to `_interopRequireWildcard(require("./myfile"))`. (see [swc tests](https://github.com/swc-project/swc/blob/cb2b0c671f9dec9a53df52aa34f9d8091ebecb98/node-swc/__tests__/module_test.js)). Strangely, jest throws the following error:

> _ReferenceError: _interopRequireWildcard is not defined_

Here is my jest config:
```js
const path = require("path");

const resolve = (_path) => path.resolve(__dirname, _path);

module.exports = {
  testURL: "http://localhost",
  testEnvironment: "jsdom",
  snapshotSerializers: ["jest-serializer-html"],
  testPathIgnorePatterns: ["e2e/", ".*donottest.*"], 
  transform: {
    "^.+\\.(t|j)sx?$": ["@swc/jest"],
  },
  setupFiles: ["jest-canvas-mock"],
  testRegex: "(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$",
  moduleFileExtensions: ["js", "jsx", "json", "ts", "tsx", "svg"],
  globals: {
    "ts-jest": {
      tsconfig: resolve("./tsconfig.test.json"),
      diagnostics: false,
    },
  },
};
```
How to fix this? All these tests run fine with `babel-jest` & `ts-jest`.

**Comment by Smrtnyk** [comment]
Maybe you need to add in your swc config the module part like
```ts
module: {
    noInterop: false
}
```

**Comment by kdy1** [comment]
I think this is fixed
