### ISSUE TITLE
Support for .mjs extension

### ISSUE THREAD

**Issue by nartc** [swc-project/jest#35]
`.mjs` extension does not pass the regex check in `process()`. Hence, transforming `.mjs` extension turns into a noop

https://github.com/swc-project/jest/blob/master/index.ts#L43

**Comment by BPScott** [comment]
I think the solution to this is just removing the if block and the regex within the plugin. As the demo jest config file in the readme file shows, you already have to filter the file names to apply the transform to, so I don't see any value on hardcoding doing that within the transform as well

```js
module.exports = {
  transform: {
    // Here's a regex of filtering what the transform applies to - no need to do this within the plugin too
    '^.+\\.(t|j)sx?$': '@swc/jest',
  },
}
```
