### ISSUE TITLE
error: Expression expected

### ISSUE THREAD

**Issue by schoening** [swc-project/jest#40]
We are currently upgrading to NextJS 12, which is using SWC rather than babel.

I wanted to give `@swc/jest` a try because of ESM module issues with babel-jest:

```SyntaxError: Cannot use import statement outside a module```

After switching from 
```'^.+\\.(js|jsx|ts|tsx)$': '<rootDir>/node_modules/babel-jest'```
to
```'^.+\\.(t|j)sx?$': '@swc/jest'```
I am getting the following errors:
```
FAIL  stories/stories.test.js
  ● Test suite failed to run

    error: Expression expected
      
       |
    36 |       <RouterContext.Provider value={mockRouter}>
       |       ^

    error: Expected ',', got 'value'
      
       |
    36 |       <RouterContext.Provider value={mockRouter}>
       |                               ^^^^^



    Caused by:
        0: failed to process js file
        1: Syntax Error
```

Is `@swc/jest` not supposed to work with `jsx`/`tsx` files? The regrex implies that it does work with it. Any suggestions?

**Comment by bodazhao** [comment]
What Jest version are you on?

**Comment by schoening** [comment]
@bodazhao 

`"jest": "^26.5.2"` I believe. At least in that particular folder. We are using a monorepo style with rush and pnpm so there are a few other versions. But this particular one uses the one I mentioned.

**Comment by schoening** [comment]
I got the babel-jest working and that is good enough for me. Would like to switch to swc tho

**Comment by vladimir-el** [comment]
@bodazhao It works on several of our projects but fails on one that uses jsx instead of tsx and has some `enzyme` tests 
```
  ● Test suite failed to run

    error: Expression expected
     
      |
    9 |     <React.Suspense fallback={<LinearProgress />}>
      |     ^
```
All of them use `"jest": "^27.3.1"`

**Comment by kdy1** [comment]
I think https://github.com/swc-project/jest/pull/44 cause the issue?

**Comment by maxhilliard** [comment]
Currently porting a test suite and had this issue. I had to set `jsx` / `tsx` to `true` to resolve this issue

```
[
  {
    "test": ".tsx?$",
    "jsc": {
      "parser": {
        "syntax": "typescript",
        "tsx": true
      },
      "target": "es5",
      "loose": false
    }
  },
  {
    "test": ".jsx?$",
    "jsc": {
      "parser": {
        "syntax": "ecmascript",
        "jsx": true,
        "decorators": false,
        "dynamicImport": false
      }
    }
  }
]
```

**Comment by KeithChasen** [comment]
@sanchezg7 God bless you, my dear savior :)
