### ISSUE TITLE
test issues, need help

### ISSUE THREAD

**Issue by vertic4l** [swc-project/jest#51]
Hey,

i've tried esbuild-jest which works better out of the box, but has issues with jest-mock() inside of test files.
Now i wanted to try swc-jest, which needs a lot more configuration and fiddling, but i don't get it to work.

In my jest.config.js we explicitly tell jest to look for these files:

`testRegex: [".spec.(ts|tsx)$"],`

but this seems to be ignored with swc-jest, cause its going through files which are not used in the test.

<img width="740" alt="Bildschirmfoto 2021-12-01 um 12 26 57" src="https://user-images.githubusercontent.com/1771763/144227083-554af129-2dda-493c-90b6-d35d1570cd73.png">

my .swcrc looks like this:

```
{
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "tsx": true,
            "decorators": true,
            "dynamicImport": true
        },
        "transform": {
            "react": {
                "development": false,
                "useBuiltins": false,
                "runtime": "automatic"
            },
            "optimizer": {
                "globals": {
                    "vars": {
                        "__DEBUG__": "true"
                    }
                }
            },
            "legacyDecorator": true,
            "decoratorMetadata": true
        },
        "target": "es5",
        "loose": false,
        "externalHelpers": true,
        "keepClassNames": false
    }
}

```

Seems to me it tries to compile the whole project

**Comment by kdy1** [comment]
This is not an issue of `swc/jest`.
