### ISSUE TITLE
.swcrc file not read

### ISSUE THREAD

**Issue by iiroj** [swc-project/jest#52]
It seems `@swc/jest` doesn't read the `.swcrc` configuration file, because Jest always passes it at least an empty options object (`swcOptions = {}`), and so this conditional never applies:

https://github.com/swc-project/jest/blob/82a6a95f2880d01e0b7e0b020a4e24bf88cb8487/index.ts#L58-L61

Something like this might help:

```diff
--- if (!swcOptions) { 
+++ if (!swcOptions || Object.keys(swcOptions).length === 0) { 
      const swcrc = path.join(process.cwd(), '.swcrc') 
      swcOptions = fs.existsSync(swcrc) ? JSON.parse(fs.readFileSync(swcrc, 'utf-8')) as Options : {} 
    } 
```

I was able to test this by cloning this repo, and moving the config in `examples/react/package.json` into `examples/react/.swcrc` instead.

**Comment by Kaciras** [comment]
Change your jest config

```javascript
transform: {
  '^.+\\.(t|j)sx?$': '@swc/jest',
},
```

to

```javascript
transform: {
  '^.+\\.(t|j)sx?$': ['@swc/jest'],
},
```

is should work.

**Comment by iiroj** [comment]
Thanks @Kaciras. Maybe the `README` could be updated for this.

**Comment by spence-novata** [comment]
I'm also having this problem, @Kaciras solution doesn't seem right to me. It gives me a type error in the IDE

<img width="632" alt="image" src="https://user-images.githubusercontent.com/91948667/147367488-ba3a3e5b-407e-461b-8dee-9468ba44d28b.png">

And then when run I get the same type error on the console

**Comment by sarneeh** [comment]
A workaround for this is:
```js
transform: {
  '^.+\\.(t|j)sx?$': ['@swc/jest', null],
},
```
