### ISSUE TITLE
Test execution does not stop at breakpoint in Intellij jest plugin

### ISSUE THREAD

**Issue by Smrtnyk** [swc-project/jest#53]
I am using jest plugin in intellij.
If I use ts-jest and set a breakpoint, while running test in debug mode using Intellij jest plugin test stops break point, but with swc it doesn't.
I suspect it has something to do with source maps.
I assume this also happens in webstorm but didn't try it.

**Comment by Smrtnyk** [comment]
I couldn't find something obvious of why it doesn't work
process function returns both code and map which should be fine
I am not an expert on source maps and not sure if that is why intellij doesn't stop at breakpoint, but if someone could have some hints I could take a stab at this.

**Comment by Smrtnyk** [comment]
I have also tried to return in process function
```ts
const suffix = `//# sourceMappingURL=${map}`;
    return `${code}\n${suffix}`;
```
but didn't help either

**Comment by Smrtnyk** [comment]
alright, figured out I need to pass in the config `sourceMaps: "inline"` for breakpoints to work

**Comment by zyf0330** [comment]
Hello, is there any other way?
