### ISSUE TITLE
jest.mock context and mock* variables

### ISSUE THREAD

**Issue by Ayc0** [swc-project/jest#59]
According to jest, `jest.mock` shouldn't depend on anything defined top level, except `mock*` variables (that seems to be hoisted in a specific way): https://jestjs.io/docs/es6-class-mocks#calling-jestmock-with-the-module-factory-parameter

![image](https://user-images.githubusercontent.com/22725671/146359944-856d484d-7485-4271-a64c-c5b67d58c3b1.png)

When the same test in run in jest without swc and with, the behavior is slightly different:

Without | With
-|-
![image](https://user-images.githubusercontent.com/22725671/146360018-53597136-b382-4682-a28b-6b52851ddfd9.png) | ![image](https://user-images.githubusercontent.com/22725671/146360035-3dab219f-62d5-4b7d-8d2a-a48f853883a1.png)

Repo to try it out: https://github.com/Ayc0/swc-jest-mock-bug

**Comment by Ayc0** [comment]
As the hoisting is handled by swc itself and not @swc/jest, I'll open this in @swc/core instead

**Comment by Ayc0** [comment]
I'm a little bit confused about how jest is handling the `mock*` variables:

Here is how babel + babel-plugin-jest-hoist handles 

```js
const mockReplace = jest.fn(() => ({ type: '' }));
jest.mock('connected-react-router', () => ({
  replace: mockReplace,
}));
```

([see REPL](https://babeljs.io/repl#?browsers=chrome%2080&build=&builtIns=usage&corejs=3.6&spec=false&loose=false&code_lz=MYewdgzgLgBAtiYBrASgUwA4BsCGw0wC8MAVmtAHQBmYAFLQJREB8MtA3jFAJ4ZoBcMAORCYAXwYMA3ACgylBMlpDQYMGmBQ0AEwC0AJzR4oBkAFct-oQBo2TQqw4yYMQ9jwD4iVJlz5rMhLSQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=true&targets=&version=7.17.1&externalPlugins=babel-plugin-jest-hoist%4027.4.0&assumptions=%7B%7D))

![image](https://user-images.githubusercontent.com/22725671/152407805-d12f9820-d692-42c8-8dcb-fffe50a1764f.png)


The variable starting in `mock` doesn't seem to get hoisted. So I don't know how they manage to make it work.

And the output seems similar in SWC ([see playground](https://play.swc.rs/?version=1.2.133&code=H4sIAAAAAAAAA02NOwqAMBAF%2B5zidUlAPUBED%2BENZF0LP0lI1kLEu4uKYD3MDAWfBWugueO49MRoMHGWavTGWDQtzAHZIztojdPaWj34Noym4D2T8FAm7knKFDbhpAt8qgLS23X%2FSaHu0gUgUawcfAAAAA%3D%3D&config=H4sIAAAAAAAAAy2KwQ3EIAwEe9k3FdDDFYHA0YFiQLYjJUL0HtDda2dHM1A0wg%2F0IEqySZ9q4YYHRQ4aJXeDW9lSRziVpoNJqHo04d1%2Fc0pUNxVSgze5aM5VZf20dJ30Uw78fwP29LWIjbnVopjzBdpGXj6IAAAA)):

![image](https://user-images.githubusercontent.com/22725671/152408092-d9aa3455-2cc2-4bea-b84f-41f1d6c18f2f.png)

**Comment by jonchurch** [comment]
The [docs](https://jestjs.io/docs/es6-class-mocks#calling-jestmock-with-the-module-factory-parameter) have since been updated to clarify what jest does:

> Since calls to `jest.mock()` are hoisted to the top of the file, Jest prevents access to out-of-scope variables. By default, you cannot first define a variable and then use it in the factory. Jest will disable this check for variables that start with the word `mock`. However, it is still up to you to guarantee that they will be initialized on time.

<img width="899" alt="Screenshot 2023-01-14 at 10 04 10 PM" src="https://user-images.githubusercontent.com/12915163/212520784-4cca82c6-bfa9-42da-af7c-48775eadbbdf.png">


Jest, and `babel-plugin-jest-hoist`, does not hoist variables prefixed with mock. Prefixing a variable in a mock factory with `mock*` only suppresses an error that would otherwise be thrown.

**Comment by Ayc0** [comment]
That makes sense.
Thanks!
