### ISSUE TITLE
source maps?

### ISSUE THREAD

**Issue by stavalfi** [swc-project/jest#6]
Thanks for this great project and this great plugin!

I'm using ndb:

![image](https://user-images.githubusercontent.com/12954665/102638175-c5227380-415f-11eb-9f4b-3ef964698687.png)

jest.config.js:

```javascript
module.exports = {
  testEnvironment: 'node',
  testRunner: 'jest-circus/runner',
  transform: {
    '^.+\\.(t|j)sx?$': ['@swc/jest'],
  },
  ....
}
```

I also have `.swcrc` file in the root folder of the project but im not sure if it's being used:

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "dynamicImport": true
    },
    "target": "es2019"
  },
  "module": {
    "type": "commonjs",
    "strict": true,
    "noInterop": false
  }
}
```

---
macos catalina 10.15.1 (19B2093)
node v15.3.0
ndb v1.1.5
@swc/jest@0.1.2
@swc/core@1.2.40

**Comment by kdy1** [comment]
Sorry for late response. I forgot about this.
You can now enable source map via swcrc.
See: https://swc.rs/docs/configuring-swc/#sourcemaps

**Comment by diegoleme** [comment]
I have the same problem here, even enabling the sourcemaps option.

![image](https://user-images.githubusercontent.com/374857/125004230-78d14f00-e02f-11eb-8cb1-f1464222fc02.png)

**Comment by diegoleme** [comment]
https://github.com/swc-project/jest/pull/12

**Comment by wongjiahau** [comment]
My problem is solved by adding the `sourceMaps: true` option.

**Comment by joshyudeep** [comment]
Did you ever encounter this issue? https://github.com/swc-project/jest/issues/47#issue-1062636830
