### ISSUE TITLE
Can't parse Flowtype file; and can't change module resolution

### ISSUE THREAD

**Issue by bozdoz** [swc-project/jest#60]
Tried the "drop-in replacement" for ts-jest, but ran into problems with a node_module that resolved to a flowtype file.  It was not able to parse the file (perhaps not surprising), and the test fails.

```
Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /workspace/node_modules/react-select/src/types.js:2
    import type { Ref } from 'react';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

I'm not sure how using this plugin instead of `ts-jest` causes this issue. i.e. I'm not sure how `ts-jest` is able to resolve to a different file.

Note: for react-select@4.3.1, the package.json file has these as its module resolutions:

```json
{
  "main": "dist/react-select.cjs.js",
  "module": "dist/react-select.esm.js",
}
```

I think it's resolving to the "module", whereas `ts-jest` is resolving from "main".  Does that make sense?  Is there some way to configure `swc/jest` to work like this?

**Comment by kdy1** [comment]
Loading is done by node js, not swc.

Are you using `paths` and `baseUrl`? If so, it can an issue.

**Comment by bozdoz** [comment]
@kdy1 Yes, tsconfig.json has `paths` and `baseUrl`.  Why would this be an issue?  Any advice?

**Comment by kdy1** [comment]
No, `swc` does not care about `package.json` if you are not using those within `.swcrc`

**Comment by bozdoz** [comment]
I have no `.swcrc` file.  I just tried a simple drop-in replacement as the main page said: https://swc.rs/docs/usage/jest

**Comment by kdy1** [comment]
Then `@swc/jest` will not care about `package.json` at all. It will consider only the input file.

I think maybe `ts-jest` is working because of `baseUrl` and `paths` in `tsconfig.json`

**Comment by bozdoz** [comment]
That seems surprising.  Should I add paths to `.swcrc`?  Is there an equivalent for `baseUrl`?

**Comment by bozdoz** [comment]
Tried out `paths` and `baseUrl` to an `.swcrc` file:

```json
{
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "tsx": true,
            "decorators": false,
            "dynamicImport": false
        },
        "baseUrl": ".",
        "paths": {
            "@": ["src"]
        }
    }
}
```

Same error.

**Comment by kdy1** [comment]
Can you try module: common js?
Btw, it seems like react-select is publishing a typescript file as esm...

**Comment by bozdoz** [comment]
added:

```json
{
    "module": {
        "type": "commonjs",
        "strict": false,
        "strictMode": true,
        "lazy": false,
        "noInterop": false
    }
}
```

Same error.

And yeah, I've had issues with `react-select` before, and a few other packages which publish improperly.  With **Webpack** I can just add:

```js
resolve: {
        mainFields: ['browser', 'main', 'module'],
}
```

And it usually resolves properly.  But, that's another issue.  Just something I thought I may have needed here too, if somehow the wrong file (the flowtype file) is being parsed.

**Comment by bozdoz** [comment]
@kdy1 Anything else I could try?

**Comment by kdy1** [comment]
Closing as this does not seem like an issue of `swc/jest`
