### ISSUE TITLE
.swcrc jsc.paths doesn't transform `jest.mock` paths

### ISSUE THREAD

**Issue by spence-novata** [swc-project/jest#63]
I've set up a few paths under `jsc.paths` in my `.swcrc` file

They are being transformed by swc nicely but when they are mocked by `jest.mock` the transformation is not done. 

Ideally this would be performed by `@swc/jest`

**Comment by shawnmcknight** [comment]
There is some prior art for this in [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver).

[Doc reference](https://github.com/tleunen/babel-plugin-module-resolver/blob/master/DOCS.md#transformfunctions)

**Comment by lsanwick** [comment]
Yeah, hitting this same issue right now. :(

**Comment by leepowellnbs** [comment]
It know it doesn't help, but just hit the same issue here.

**Comment by camilossantos2809** [comment]
I'm actually still running into this, any workarounds?

**Comment by seanparmelee** [comment]
@kdy1 I see this now moved over to https://github.com/swc-project/pkgs. Do you need us to log this issue over there as well?

**Comment by kdy1** [comment]
No. I'll close this issue as wontfix.
See https://github.com/swc-project/swc/issues/7435.
`jest.mock` of ESM should fail
