### ISSUE TITLE
Running @swc/jest@0.2.15 on Github actions results in "Cannot find module '@swc/core-linux-x64-gnu'"

### ISSUE THREAD

**Issue by alexbjorlig** [swc-project/jest#69]
Is there a fix for this issue, running on Github actions?

**Comment by kdy1** [comment]
Install `@swc/core`. It's peer dependency.
https://github.com/swc-project/jest/blob/ff779d7dbe53f9ffdb80266f7f99b0e43989e824/package.json#L25

**Comment by alexbjorlig** [comment]
Thanks for the fast response. I still get this error `'@swc/core-linux-x64-gnu'`

![Screen Shot 2022-01-13 at 16 17 40](https://user-images.githubusercontent.com/9967422/149357231-d1580f60-e222-43e3-9f53-842b46884254.png)

My package.json looks like this:

```
"devDependencies": {
  "@swc/core": "^1.2.129",
  "@swc/jest": "^0.2.17",
}
```
