### ISSUE TITLE
jsx runtime with @swc/jest

### ISSUE THREAD

**Issue by rodoabad** [swc-project/jest#70]
With React's new JSX runtime, we no longer need to import `React`. This causes issues when transforming with `@swc/jest` since it throws a React is undefined error.

https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html

**Comment by kdy1** [comment]
You can configure swc to use automatic runtime by using swcrc

**Comment by jayalfredprufrock** [comment]
That configuration allows omitting the React import within src files but importing react still seems to be required in the tests themselves. Is that to be expected? I don't remember that limitation before when using the babel transform.

**Comment by alexgwolff** [comment]
Short response

.swcrc

```json
{
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    }
}

```

**Comment by vitalyster** [comment]
Does not work for me.
```
{
    "jsc": {
        "transform": {
            "react": {
                "runtime": "automatic"
            }
        }
    }
}
```

**Comment by vitalyster** [comment]
Well, found the correct config adopted to javascript:
```
{
    // .swcrc should be treated as JSONC
  
    "sourceMaps": true,
  
    "jsc": {
      "parser": {
        "syntax": "ecmascript",
        "jsx": true
      },
  
      "transform": {
        "react": {
          "runtime": "automatic"
        }
      }
    }
  }
```
