### ISSUE TITLE
TypeError: Cannot set property myVariable of [object Object] which has only a getter

### ISSUE THREAD

**Issue by CyrilQuandalle** [swc-project/jest#72]
Hello,

I'm trying to use this on my mono repo project and for some tests I have the following error :

`TypeError: Cannot set property myVariable of [object Object] which has only a getter`

myVariable is declared like that in a file external to the test files :

`export const registerSettingsIntegrationDatalayer = () => myfunction()`

I also tried to make my function return a string just for a dummy try but I got the same error.

I'm using @swc/core : **^1.2.137** and @swc/jest : **^0.2.17** and here is my swc configuration :

```
{
      "jsc": {
        "parser": {
          "syntax": "typescript",
          "tsx": true,
          "dynamicImport": true,
          "privateMethod": false,
          "functionBind": false,
          "exportDefaultFrom": true,
          "exportNamespaceFrom": false,
          "decorators": false,
          "decoratorsBeforeExport": false,
          "topLevelAwait": false,
          "importMeta": false
        },
        "transform": {"react": {"runtime": "automatic"}},
        "target": "es5",
        "loose": false,
        "externalHelpers": false,
        "keepClassNames": false,
      },
      "sourceMaps": true
    }
```

Is there something in my configuration that I could modify to fix my issue ?

Thanks in advance

**Comment by samhh** [comment]
I'm seeing the same issue trying to migrate from `esbuild-jest`.

I've identified that the issue presents when trying to export a named export which is also implicitly exported by an `export *` declaration. A specific example that I suspect will repro outside of our specific repo:

```ts
// includes a `format` export
export * from 'fp-ts-routing'

export const format = 'anything'
```

**Comment by CyrilQuandalle** [comment]
Thanks @samhh you were right I had an export exporting exactly the same variable from another file in my file.
I think the error should be more explicit or at least it shouldn't raise an error like when running vanilla Jest with typescript.

Now the next issue that be great to be fixed is the `jest.spyOn` already referenced in an existing issue ;-)

**Comment by Svenskunganka** [comment]
Also seems to happen with this code:

```js
import * as something from 'somewhere';

something.someProp = jest.fn();
```

**Comment by derN3rd** [comment]
Does someone has an example of the correct usage of spyOn then?

We are currently using it like this

```ts

import * as UsageAmounts from '../../../src/getUsageAmounts'

[...]

  jest
    .spyOn(UsageAmounts, 'getUsageAmounts')
    .mockResolvedValueOnce({ amount: 12 })
```

Which also leads to the `TypeError: Cannot redefine property: getUsageAmounts        at Function.defineProperty (<anonymous>)` error when switching to swc

**Comment by Smrtnyk** [comment]
@derN3rd can you try with swc 194?

**Comment by derN3rd** [comment]
Just tried it with 
- @swc-node/core@1.9.1
- @swc-node/jest@1.5.5
- @swc/core@1.2.194

And the issue is gone. Thanks, gonna use that for now

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/issues/5205
