### ISSUE TITLE
Consider defaulting jsc target to the current Node version's supported level

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [swc-project/jest#74]
Generators and async/await have been [fully supported in Node for years](https://kangax.github.io/compat-table/es2016plus/#node8_10), but the default SWC options are still set to transpile them to using [regenerator-runtime](https://www.npmjs.com/package/regenerator-runtime). Since `@swc/jest` is specifically for usage in Jest, if there isn't a `jsc.target` specified in `.swcrc` or the Jest config, can it default to whatever level is supported by the runtime Node version?

Reasoning: it's a little extra work for projects that don't yet have a SWC configuration to specify a `jsc` target. https://swc.rs/docs/usage/jest indicates your Jest configuration only needs to include:

```js
module.exports = {
  transform: {
    "^.+\\.(t|j)sx?$": ["@swc/jest"],
  },
};
```

...but in actuality, if this is your first swc setup, you need something more like:

```js
module.exports = {
    transform: {
        "^.+\\.(t|j)s$": [
            "@swc/jest",
            {
                jsc: {
                    target: "es2021",
                },
            },
        ],
    },
};
```

...which is a pain point for new SWC users and a bit of noisy configuration.

**Comment by kdy1** [comment]
It sounds good to me.
