### ISSUE TITLE
No way to override jsc or module swc configuration?

### ISSUE THREAD

**Issue by dbjorge** [swc-project/jest#8]
It doesn't appear that there's any way to customize `swc`'s `jsc` or `module` configuration with `@swc/jest`.

The options passed to `transformSync` are built up like this:

https://github.com/swc-project/jest/blob/6281cfbfdb63562acbca4fcdf49e7ea77c562e57/index.ts#L9-L23

 `.swcrc` seems to be ignored, and the overrides to the `jsc` and `module` properties mean that even if you pass transformer options in `jest.config.js`, configuration for other properties under `jsc`/`module` will be discarded.

Ideally, I think the behavior would be for the options passed to `transformSync` to use your `.swcrc` options by default, then override just the specific subproperties required for Jest compat (commonjs + hidden.jest), then override with any explicit transformOptions.

It would also be nice to:
* Support a specific transformOption to override where to look for the `.swcrc` file, similar to how `@swc/cli` supports a --config-file option.
* Document (in both the readme here and https://swc.rs/docs/usage-swc-jest/) how configuration works and include an example of specifying transformer options

Context: hit this while attempting to apply `noInterop: true` as a workaround for https://github.com/swc-project/swc/issues/1778

**Comment by buschtoens** [comment]
This is now actually a major blocker for using ESM in jest (https://github.com/facebook/jest/issues/9430).

When I comment out the line that forces `commonjs`:

https://github.com/swc-project/jest/blob/9d81a9a2d8a719843a78386031de1a91a30ef9c1/index.ts#L48

And use these configs:

```js
// jest.config.js
/** @type {import('@jest/types').Config.InitialOptions} */
module.exports = {
  // testEnvironment: 'jsdom', // Irrelevant for the bug. Enable at will.
  transform: {
    '^.+\\.tsx?$': '@swc/jest'
  },
  extensionsToTreatAsEsm: ['.ts']
};
```

```js
// .swcrc
{
  "sourceMaps": true,
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true, // Might as well be false, if not transpiling `.tsx`.
      "decorators": false,
      "dynamicImport": true // Required.
    },
    "target": "es2020",
    "loose": true
  }
}
```

ESM and jest work just fine, with the limitations noted in the tracking issue: https://github.com/facebook/jest/issues/9430

**Comment by kdy1** [comment]
I'll take a look soon.

**Comment by kdy1** [comment]
Fixed with the new version of `@swc/jest`.
You can use `v0.2.0` to do this.

**Comment by buschtoens** [comment]
Much appreciated! Thank you. 💖

![](https://media.giphy.com/media/o3PanN3hBOACPG25xF/giphy.gif)

What do you think a good long-term plan would be for the config patching? AFAICT, these options are crucial when wanting to use TypeScript & ESM with jest:

```ts
{
  "sourceMaps": true,         // Important
  "jsc": {
    "parser": {
      "syntax": "typescript", // Important
      "tsx": true,            // Depending on whether `.tsx` is targeted as well.
      // "decorators": false,
      "dynamicImport": true   // Important.
    },
    "target": "es2020"        // I think that was important for dynamic import stuff.
  },
  "module": null              // Important
}
```
```ts
{
  transform: {
    '^.+\\.tsx?$': '@swc/jest'
  },
  extensionsToTreatAsEsm: ['.ts', '.tsx']
}
```

It would be nice, if these options could eventually be applied correctly out-of-the-box.

**Comment by kdy1** [comment]
```json
{
  "sourceMaps": true,         // Maybe this should be true by default.
  "jsc": {
    "parser": {
      "syntax": "typescript", // Should be specified, because jest can be used with non-ts codes.
      "tsx": true,            // Making this true will just work, if it's accepted by tsc
      // "decorators": false,
      "dynamicImport": true   // If this is required by jest? If so, it should be default
    },
    "target": "es2020"        // Not important for dynamic imports.
  },
  "module": null              // This is null by default
}
```
