### ISSUE TITLE
ESM support not working

### ISSUE THREAD

**Issue by Yxwww** [swc-project/jest#99]
Hi there 👋  thanks in advance for having a look at this issue. 

I was trying to setup a boiler plate repo for a typescript library. I aim to bring swc into the repo. It all works great until I turn on ESM mode in package.json by setting `"types": "module"`. 

The boilerplate repo is [https://github.com/Yxwww/ts-library-boilerplate](https://github.com/Yxwww/ts-library-boilerplate). See the error in github actions [here](https://github.com/Yxwww/ts-library-boilerplate/runs/6514923935?check_suite_focus=true#step:5:9).

### Copy of Error
```
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/work/ts-library-boilerplate/ts-library-boilerplate/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/runner/work/ts-library-boilerplate/ts-library-boilerplate/jest.config.js:1:1
    at ModuleJob.run (node:internal/modules/esm/module_job:1[9](https://github.com/Yxwww/ts-library-boilerplate/runs/6514923935?check_suite_focus=true#step:5:10)8:25)
    at async Promise.all (index 0)
```

The error seems to suggest there's some issue with `.js` file which the repo only contains ts file. I wonder if my config is incorrect causes out of order transform sequence ? 

## Steps I used to setup

Pretty much followed what's specific in readme:

1. `"type": "module"` in package.json
2. `extensionsToTreatAsEsm: ['.ts', '.tsx'],` in jest.config
3. `NODE_OPTIONS=--experimental-vm-modules jest` for test script in package.json

**Comment by kdy1** [comment]
Seems like `@swc/jest` defaulting to common js is the issue?
https://github.com/swc-project/jest/blob/52c516b19b4d37e431e55afdc7eabbf9032da04a/index.ts#L35

Can you try `supportsStaticESM`?

**Comment by simonhammes** [comment]
Renaming `jest.config.js` to `jest.config.cjs` did the trick for me (I cloned your repository and ran `npm test` afterwards).

**Comment by Yxwww** [comment]
@simonhammes  👍  worked on my end as well. 

It's funny I went back to re-read the error message again it literally suggesting to rename jest.config to `.cjs` extension. For some reason I thought it was suggestion the jest config is causing jest to run some `.js` file mid transpilation. 🤷‍♂️ 

Anyways, thanks for looking into it, folks!
